---
name: Build Docker Container

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Buildah Build
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: tictactoe-game
          tags: latest ${{ github.sha }}
          dockerfiles: ./Dockerfile

      - name: Publish Image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/SoBeRBot94
          username: SoBeRBot94
          password: ${{ secrets.GITHUB_TOKEN }}
