name: Container Image Build Workflow

on:
  pull_request:
    branches: [master]

env:
  REGISTRY_USER: ${{ github.actor }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_PASS: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and Push Buildah Image
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout The Repository
        uses: actions/checkout@v2

      - name: Buildah Build Image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ github.repository }}
          tags: latest, ${{ github.run_number }}
          dockerfiles: |
            ./Dockerfile

      - name: Login to Github Registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASS }}
          registry: ${{ env.IMAGE_REGISTRY }}
