---
name: Build Docker Container

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ github.actor }}/tictactoe-game:latest, ${{ github.actor }}/tictactoe-game:${{ github.run_number }}
